/*
============================================================
TOPIC 7 : GROUP BY

Name : Sanjay Kumar S
Reg No: RA2311026010321
============================================================
*/


/*
============================================================
Q1. Studio Negotiation

Management wants to know how movies are distributed
across genres.
============================================================
*/

SELECT
    genre,
    COUNT(*) AS Number_Of_Movies
FROM movie
GROUP BY genre;

/*
Sanjay Kumar S - RA2311026010321
*/


/*
============================================================
Q2. Payment Health Dashboard

Show payment counts by status.
============================================================
*/

SELECT
    status,
    COUNT(*) AS Payment_Count
FROM payment
GROUP BY status;

/*
Sanjay Kumar S - RA2311026010321
*/


/*
============================================================
Q3. Social Media Buzz Report

Determine how many reviews each movie has received.
============================================================
*/

SELECT
    movie_id,
    COUNT(*) AS Review_Count
FROM review
GROUP BY movie_id;

/*
Sanjay Kumar S - RA2311026010321
*/


/*
============================================================
Q4. Food Delivery Strategy

Calculate revenue generated by each delivery method.
============================================================
*/

SELECT
    delivery_method,
    SUM(total_amount) AS Total_Revenue
FROM foodorder
GROUP BY delivery_method;

/*
Sanjay Kumar S - RA2311026010321
*/


/*
============================================================
Q5. Casting Cost Analysis

Determine the number of cast members in each movie.
============================================================
*/

SELECT
    movie_id,
    COUNT(*) AS Cast_Count
FROM moviecast
GROUP BY movie_id;

/*
Sanjay Kumar S - RA2311026010321
*/